.TH PMC 8 "October 2013" "linuxptp"
.SH NAME
pmc \- PTP management client

.SH SYNOPSIS
.B pmc
[
.BI \-f " config-file"
] [
.B \-2
|
.B \-4
|
.B \-6
|
.B \-u
] [
.BI \-b " boundary-hops"
] [
.BI \-d " domain-number"
] [
.BI \-i " interface"
] [
.BI \-s " uds-address"
] [
.BI \-t " transport-specific-field"
] [
.I long-options
] [
.B \-v
] [
.B \-z
] [ command ] ...

.SH DESCRIPTION
.B pmc
is a program which implements a PTP management client according to IEEE
standard 1588. The program reads from the standard input or from the command
line actions specified by name and management ID, sends them over the selected
transport and prints any received replies. There are three actions supported:
.B GET
retrieves the specified information,
.B SET
updates the specified information and
.B CMD
(or
.BR COMMAND )
initiates the specified event.

By default the management commands are addressed to all ports. The
.B TARGET
command can be used to select a particular clock and port for the
subsequent messages.

Command
.B help
can be used to get a list of supported actions and management IDs.

.SH OPTIONS
.TP
.BI \-f " config-file"
Read configuration from the specified file. No configuration file is read by
default.
.TP
.B \-2
Select the IEEE 802.3 network transport.
.TP
.B \-4
Select the UDP IPv4 network transport. This is the default transport.
.TP
.B \-6
Select the UDP IPv6 network transport.
.TP
.B \-u
Select the Unix Domain Socket transport.
.TP
.BI \-b " boundary-hops"
Specify the boundary hops value in sent messages. The default is 1.
.TP
.BI \-d " domain-number"
Specify the domain number in sent messages. The default is 0.
.TP
.BI \-i " interface"
Specify the network interface. The default is /var/run/pmc.$pid for the Unix Domain
Socket transport and eth0 for the other transports.
.TP
.BI \-s " uds-address"
Specifies the address of the server's UNIX domain socket.
The default is /var/run/ptp4l.
.TP
.BI \-t " transport-specific-field"
Specify the transport specific field in sent messages as a hexadecimal number.
The default is 0x0.
.TP
.B \-h
Display a help message.
.TP
.B \-v
Prints the software version and exits.
.TP
.B \-z
The official interpretation of the 1588 standard mandates sending
GET actions with valid (but meaningless) TLV values. Therefore the
pmc program normally sends GET requests with properly formed TLV
values. This option enables the legacy option of sending zero
length TLV values instead.

.SH LONG OPTIONS

Each and every configuration file option (see below in sections
.BR PROGRAM\ OPTIONS
and
.BR PORT\ OPTIONS )
may also appear
as a "long" style command line argument. For example, the transportSpecific
option may be set using either of these two forms:

.RS
\f(CW\-\-transportSpecific 1   \-\-transportSpecific=1\fP
.RE

Option values given on the command line override values in the global
section of the configuration file (which, in turn, overrides default
values).

.SH CONFIGURATION FILE

The configuration file is divided into sections. Each section starts with a
line containing its name enclosed in brackets and it follows with settings.
Each setting is placed on a separate line, it contains the name of the
option and the value separated by whitespace characters. Empty lines and lines
starting with # are ignored.

The global section (indicated as
.BR [global] )
sets the global program options as well as the default port specific options.
Other sections are port specific sections and they override the default port
options. The name of the section is the name of the configured port (e.g.
.BR [eth0]
).

.SH PROGRAM OPTIONS
.TP
.B domainNumber
The domain attribute of the local clock. The default is 0.

.SH PORT OPTIONS
.TP
.B transportSpecific
The transport specific field. Must be in the range 0 to 255.
The default is 0.

.TP
.B network_transport
Select the network transport. Possible values are UDPv4, UDPv6 and L2. The default
is UDPv4.

.TP
.B ptp_dst_mac
The MAC address to which PTP management messages should be sent. Relevant only with L2 transport. The default is 01:1B:19:00:00:00.


.SH MANAGEMENT IDS

.TP
.B ANNOUNCE_RECEIPT_TIMEOUT
.TP
.B CLOCK_ACCURACY
.TP
.B CLOCK_DESCRIPTION
.TP
.B CURRENT_DATA_SET
.TP
.B DEFAULT_DATA_SET
.TP
.B DELAY_MECHANISM
.TP
.B DOMAIN
.TP
.B GRANDMASTER_SETTINGS_NP
.TP
.B LOG_ANNOUNCE_INTERVAL
.TP
.B LOG_MIN_PDELAY_REQ_INTERVAL
.TP
.B LOG_SYNC_INTERVAL
.TP
.B NULL_MANAGEMENT
.TP
.B PARENT_DATA_SET
.TP
.B PORT_DATA_SET
.TP
.B PORT_DATA_SET_NP
.TP
.B PORT_PROPERTIES_NP
.TP
.B PORT_STATS_NP
.TP
.B PRIORITY1
.TP
.B PRIORITY2
.TP
.B SLAVE_ONLY
.TP
.B TIMESCALE_PROPERTIES
.TP
.B TIME_PROPERTIES_DATA_SET
.TP
.B TIME_STATUS_NP
.TP
.B TRACEABILITY_PROPERTIES
.TP
.B USER_DESCRIPTION
.TP
.B VERSION_NUMBER

.SH WARNING

Be cautious when the same configuration file is used for both ptp4l
and pmc.  Keep in mind that values specified in the configuration file
take precedence over their default values. If a certain option which
is common to ptp4l and pmc is specified to a non-default value in the
configuration file (e.g. for ptp4l), then this non-default value
applies also for pmc. This might be not what is expected.

To avoid securely these unexpected behaviour, different configuration files
for ptp4l and pmc are recommended.

.SH SEE ALSO
.BR ptp4l (8)
