.TH SNMP4LPTP 8 "September 2018" "linuxptp"
.SH NAME
snmp4lptp - SNMP sub agent

.SH SYNOPSIS
.B snmp4lptp
[
.BI \-f " config-file"
] [
.B \-m
] [
.B \-q
] [
.I long-options
]

.SH DESCRIPTION
.B snmp4lptp
is an implementation of a sub agent for handling SNMP requests on
the device running ptp4l. Via the UDS port, the sub agent retrieves
management information from ptp4l and translates the information to
or from an SNMP-specific form. 

.SH OPTIONS
.TP
.BI \-f " file"
Specify the path to the \fBsnmp4lptp\fR configuration file.
.TP
.B \-h
Display a help message.
.TP
.B \-m
Print messages to the standard output.
.TP
.B \-q
Don't send messages to the system logger.

.SH LONG OPTIONS

Each and every configuration file option (see below in sections
.BR PROGRAM\ OPTIONS
and
.BR PORT\ OPTIONS )
may also appear
as a "long" style command line argument. For example, the transportSpecific
option may be set using either of these two forms:

.RS
\f(CW\-\-transportSpecific 1   \-\-transportSpecific=1\fP
.RE

Option values given on the command line override values in the global
section of the configuration file (which, in turn, overrides default
values).

.SH CONFIGURATION FILE

The configuration file is divided into sections. Each section starts with a
line containing its name enclosed in brackets and it follows with settings.
Each setting is placed on a separate line, it contains the name of the
option and the value separated by whitespace characters. Empty lines and lines
starting with # are ignored.

The global section (indicated as
.BR [global] )
sets the global program options as well as the default port specific options.
Other sections are port specific sections and they override the default port
options. The name of the section is the name of the configured port (e.g.
.BR [eth0]
). Currently no port specific options other than default are considered.

.SH PROGRAM OPTIONS
.TP
.B domainNumber
The domain attribute of the local clock.
The default is 0.
.TP
.B logging_level
The maximum logging level of messages which should be printed.
The default is 6 (LOG_INFO).
.TP
.B message_tag
The tag which is added to all messages printed to the standard output or system
log.
The default is an empty string (which cannot be set in the configuration file
as the option requires an argument).
.TP
.B use_syslog
Print messages to the system log if enabled.
The default is 1 (enabled).
.TP
.B verbose
Print messages to the standard output if enabled.
The default is 0 (disabled).
.TP
.B uds_address
Specifies the address of the server's UNIX domain socket.
The default is /var/run/ptp4l.

.SH PORT OPTIONS
.TP
.B transportSpecific
The transport specific field. Must be in the range 0 to 255.
The default is 0.

.SH WARNING

Be cautious when the same configuration file is used for both ptp4l
and snmp4lptp. Keep in mind that values specified in the configuration
file take precedence over their default values. If a certain option which
is common to ptp4l and snmp4lptp is specified to a non-default value in
the configuration file (e.g. for ptp4l), then this non-default value
applies also for snmp4lptp. This might be not what is expected.

To avoid securely these unexpected behaviour, different configuration files
for ptp4l and snmp4lptp are recommended.

.SH SEE ALSO
.BR ptp4l (8)
